### ISSUE TITLE
Partitioning scripts doesnt remove old partitions

### ISSUE THREAD

**Issue by mbuyukkarakas** [zabbix-book/partitiontables_zabbix#1]
Hello all,

I used this script in my local environment with zbx 3.4 + mysql 5.7.
It is ok when the partititoning runs but it does not remove old partitions. I decreased the values to the lowest.
HISTORY_DAYS=7
TREND_MONTHS=12

What should I check first ?

Thank you.
Mehmet

**Comment by zhausong** [comment]
check  crontab 
```
shell# crontab -e
1 0 * * * /usr/sbin/partitiontables_zabbix.sh
Shell# chmod 700 /usr/sbin/partitiontables_zabbix.sh
```
and then check by this
```
bash -x /usr/sbin/partitiontables_zabbix.sh
```
